learning_log/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
# from . import learning_logs

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace = 'users')),
    path('', include(('learning_logs.urls', 'learning_logs'), namespace = 'learning_logs')),
]

learning_logs/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    # 主页
    re_path(r'^$', views.index, name = "index"),

    # 显示所有主题
    re_path(r'^topics/$', views.topics, name = "topics"),

    # 特定主题的详细页面
    re_path(r'^topics/(?P<topic_id>\d+)/$', views.topic, name = 'topic'),

    # 用于添加新主题的网页
    re_path(r'^new_topic/$', views.new_topic, name = 'new_topic'),

    # 用于添加新条目的页面
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name = 'new_entry'),

    # 用于编辑现有条目
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name = 'edit_entry')
]

users/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    # 登录
    re_path(r'^login/$', views.userlogin, name = 'userlogin'),
    # 注销
    re_path(r'^logout/$', views.userlogout, name = 'logout'),
    # 注册
    re_path(r'^register/$', views.register, name = 'register')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text = models.CharField(max_length = 200)
    date_added = models.DateTimeField(auto_now_add = True)
    owner = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete = models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add = True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        # """返回模型的字符串表示"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect,Http404
# from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')

from .models import Topic

@login_required
def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner = request.user ).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

@login_required
def topic(request, topic_id):
    """显示主题下的所有条目"""
    topic = Topic.objects.get(id = topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

from .forms import TopicForm

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据: 创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据, 对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit = False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

from .forms import EntryForm

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id = topic_id)

    if request.method != 'POST':
        # 未提交数据, 创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据, 对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit = False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {
        'topic': topic,
        'form': form,
    }
    return render(request,'learning_logs/new_entry.html',context )

from .models import Entry
@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id = entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # 初次请求, 使用当前条目填充表单
        form = EntryForm(instance = entry)
    else:
        # POST提交的数据修改Entry
        form = EntryForm(instance = entry, data = request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic', args = [topic.id]))
    
    context = {
        'entry': entry,
        'topic': topic,
        'form': form
    }
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
# Create your views here.
from django.contrib.auth import authenticate, login, logout
# from django.contrib.auth.views import LoginView
def userlogin(request):
    """用户登录"""
    if request.method != "POST":
        context = {}
    else:
        username = request.POST['username']
        password = request.POST['password']
        
        user = authenticate(request, username = username, password = password)
        print(user)
        if user is not None:
            login(request, user)
            # redirect
            return HttpResponseRedirect(reverse("learning_logs:index"))
        else:
            # return an error message
            context = {"error_message":"Could not log in, please check your accout."}
        
    return render(request,'users/login.html', context)


# 注销
def userlogout(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse("learning_logs:index"))

# 注册
from django.contrib.auth.forms import UserCreationForm

def register(request):
    """ 注册新用户 """
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录, 再重定向到主页
            authenticated_user = authenticate(username = new_user.username, 
                password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Learning Log</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics <span class="sr-only">(current)</span></a>
                    </li>
                
                    {% comment %} <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Dropdown
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li> {% endcomment %}
                </ul>
                <ul class="navbar-nav navbar-right">
                    {% if user.is_authenticated %}

                        <li class="nav-item">
                            <a class="nav-link" href="#">Hello, {{ user.username }}</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href = "{% url 'users:logout' %}">log out</a>
                        </li>

                    {% else %}

                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href = "{% url 'users:userlogin' %}">log in</a>
                        </li>

                    {% endif %}
                </ul>
                
                {% comment %} <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form> {% endcomment %}
            </div>
        </nav>
        <div class="container mt-5">
            <div class="page-header">
                {% block header %}{% endblock header%}
            </div>
            <div>
                {% block content%} {% endblock content %}
            </div>
        </div>
    </body>


{% comment %} <!DOCTYPE html>
<html>
<body>
    <p>
        <a href="{% url 'learning_logs:index' %}">Learning Log</a> - 
        <a href="{% url 'learning_logs:topics' %}">Topics</a>
        {% if user.is_authenticated %}
            Hello, {{ user.username }}
            <a href = "{% url 'users:logout' %}">log out</a>
        {% else %}
            <a href="{% url 'users:userlogin' %}">log in</a>
            <a href="{% url 'users:register' %}">register</a>
        {% endif %}
    </p>
    {% block content%} {% endblock content %}
</body>
</html> {% endcomment %}

learning_logs/templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <h2>Edit topic: 
        <a href = "{% url 'learning_logs:topic' topic.id %}">{{topic.text}}</a>
    </h2>
{% endblock header %}

{% block content %}

    <form class="form" action = "{% url 'learning_logs:edit_entry' entry.id%}" method = "post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" name = "submit" >Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
<div class="jumbotron">
  <h1 class="display-4">Track your learning.</h1>
</div>
{% endblock header%}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
       Whenever you learn something new about a topic, make an entry
       summarizing what you've learned.
    </h2>
    
{% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <h2>Add a new entry for topic: 
        <small><a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></small>
    </h2>
{% endblock header%}
  
{% block content %}

    <form class="form" action = "{% url 'learning_logs:new_entry' topic.id %}" method = "post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button class="btn btn-primary" name = "submit">Add entry</button>
        {% endbuttons %}

    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block header %}
    <h2>Add a new topic:</h2>
{% endblock header %}

{% block content %}

    <form class="form" action = "{% url 'learning_logs:new_topic' %}" method = 'post' >
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button class="btn btn-primary" name="submit">Add topic</button>
        {% endbuttons%}
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
    <p>
        <a href = "{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
    </p>
        {% for entry in entries %}
            <div class="card-group">
                <div class="card mb-3">
                    <div class="card-header">
                        <h3>
                            {{ entry.date_added | date:'M d, Y H:i' }}
                            <small>
                                <a href = "{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
                            </small>
                        </h3>
                    </div>
                    <div class="card-body">
                        <p class="card-text">
                            {{ entry.text | linebreaks }}
                        </p>
                    </div>
                </div>
            </div>
        {% empty %}
            No entry has been added yet.
        {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block header %}
    <h1>Topics</h1>
{% endblock header %}

{% block content %}
    <p>Topics</p>
        <ul>
            {% for topic in topics %}
               <li>
                <h3>
                    <a href = "{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
                </h3>
               </li>
            {% empty %}
                <li>No topics have been added yet.</li>
            {% endfor %}
        </ul>
        <h3>
            <a href = "{% url 'learning_logs:new_topic' %}">Add a new topic</a>
        </h3>
{% endblock content %}

users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock header %}

{% block content %}

    <form class="form" action="{% url 'users:userlogin' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label>Username</label>
            <input type="text" name="username" class="form-control" placeholder="Enter your username">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password"  name="password"  class="form-control" placeholder="Enter your password">
        </div>
        {% buttons %}
            <button type="submit" class="btn btn-primary">Login</button>
        {% endbuttons %}

    </form>
    {% if error_message %}
        <div class="alert alert-danger" role="alert">
           {{error_message}}
        </div>
    {% endif %}
{% endblock content %}

users/templates/users/register.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}
{% block header %}
    <h2>Register</h2>
{% endblock header%}

{% block content %}

    <form class="form" action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
    </form>

{% endblock content %}